#!/usr/bin/anv bash
#script tell a story using passwd 
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7;
do
      echo "The user $f1 is part of the $f4 clique, lives in $f6 and rides $f7. $f3's place is secured by passwd $f2, more information on: $f5"
done</etc/passwd
