#!/usr/bin/env bash
#script to output Best School ten times using while loop with 8th and 4th having different output bashed  on the conditions faced 
COUNT=0
while((COUNT<10));do
        if [ "$COUNT" -eq 7 ] ;then
                echo "good luck"
        elif ["$COUNT" -eq 3 ] ;then
               echo "bad luck"
        else
               echo "Best School"
        fi
((COUNT++))
done; 
