#!/usr/bin/env bash
#script to output 20 numbers
COUNT=1
while((COUNT<=20));do
       echo "$COUNT"
       case $COUNT in
               4) echo "bad luck from China"
                       ;;
               9) echo "bad luck from Japan"  
                       ;;
               17) echo "bad luck from Italy"
                       ;;
        esac
((COUNT++))
done;
              


