#!/usr/bin/env bash
#script does various output
FILE=$( find . -name "school" |cut -d "/" -f2)
if [ -e "$FILE" ] ;then
       echo "school file exists"
       if [ -s "$FILE" ] ;then
               echo "school file is not empty"
       elif [ ! -s "$FILE" ] ;then
               echo "school file is empty"
       fi
       if [ -f "$FILE" ] ;then
               echo "school is a regular file"
       fi
else
       echo "school file does not exist"
fi
